---
name: Bug / Typo / Error in Ontology Content
about: Report a bug, typo, or other error found in the ontology's content
title: "[Typo/Bug] "
labels: bug, typo
---

## Term affected
The ID and label of the term where the issue was found, if applicable.

## Description of the bug, typo, or error
A clear description of the problem.

## Additional information (optional)
Anything else relevant to the request that isn't captured above.

## Contributor
If you would like to be credited, please provide your ORCID (or similar
identifier).

## Source reference for template
This template was synthesized from the templates for similar issue types of OBO Foundry (https://obofoundry.org)
issue templates. The specific source of each block is specified in the PROVENANCE.md file (link). All repositories used for inspiration for this template is referenced here:

agro/bugs-errors.yml, cl/h_typos_bugs.md, mondo/typos-bugs-errors.md, pbpko/typos-bugs-errors.md, uberon/g_typos_bugs.md